In [1]:
import numpy as np

# Introdução a Matrizes


In [10]:
M_zeros = np.zeros((3, 3)) #matriz 3x3, primeiro argumento é o shape
M_ones = np.ones((3, 3)) #matriz 3x3, primeiro argumento é o shape
M_full = np.full((3, 3), 7) #matriz 3x3 de 7s
M_rand = np.random.rand(3, 3) #matriz 3x3 de 0 e 1 (rand)
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #lista de listas
M_ident = np.eye(3) #matrisz identidade 3x3
M_diag = np.diag([1, 2, 3]) #matriz diagonal com esses valores na diagonal principal
M_diagsec = np.diag([1, 2], 1) #faz a diagonal um indice acima
M_diagmatriz = np.diag(M_ident) #retorna a diagonal dessa matriz
Mt = M.T #matriz transposta (não é função)
vetor = np.array([1, 2, 3, 4, 5, 6])
M_reshape = vetor.reshape((2, 3))

print(M_zeros)
print(M_ones)
print(M_full)
print(M_rand)
print(M)
print(M_ident)
print(M_diag)
print(M_diagsec)
print(M_diagmatriz)
print(Mt)
print(vetor)
print(M_reshape)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.13364508 0.06502504 0.30520769]
 [0.25345759 0.37119617 0.54166485]
 [0.49687262 0.03267844 0.44804535]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0]
 [0 0 2]
 [0 0 0]]
[1. 1. 1.]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Operações com Matrizes

In [17]:
#Soma de matrizes
M_soma = M + M_ones
print(M_soma)
print(20 * "-")

M_mult = M @ M_ones
print(M_mult)
print(20 * "-")

M_multElem = M * M_ones #multiplica elemento a elemento
print(M_multElem)
print(20 * "-")

#soma matriz-vetor (soma o vetor a todas as colunas)
vetor = np.array([1, 2, 3])
M_somaArray = M + vetor
print(M_somaArray)
print(20 * "-")

#Acesso
print(M[0, 0])
print(20 * "-")
print(M[:, 0]) #primeira coluna
print(20 * "-")
print(M[0, 1:3]) #primeira linha, do primeiro ao segundo elemento
print(20 * "-")

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
--------------------
[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]
--------------------
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
--------------------
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
--------------------
1
--------------------
[1 4 7]
--------------------
[2 3]
--------------------


# Exercicio:
criar matriz de projeção em um vetor qualquer

In [21]:
#maneira generica: proj = np.outter(u, u) / np.dot(u, u), produto externo de u com u vezes 1 / norma ao quadrado de u
def proj_mat(u):
    proj =  np.array([
        [u[0] ** 2, u[0] * u[1]],
        [u[0] * u[1], u[1] ** 2]
    ])

    proj /= np.dot(u, u)
    return proj

def proj_mat2(u):
     print(np.outer(u, u) / np.dot(u, u))

u = np.array([4.0, 3.0])
M_proj = proj_mat(u)
print("Matriz de Projecao")
print(M_proj)

vet = np.array([1, 2])
vet_proj = M_proj @ vet
print(vet_proj)

proj_mat2(u)

Matriz de Projecao
[[0.64 0.48]
 [0.48 0.36]]
[1.6 1.2]
[[0.64 0.48]
 [0.48 0.36]]
