In [2]:
import numpy as np

# Exercicio 02:
Considere os dados da tabela:
| País         | PIB (trilhões USD) | População (milhões) | Inflação (%) | Desemprego (%) |
|--------------|---------------------|----------------------|--------------|----------------|
| Brasil       | 2.1                 | 213                  | 3.2          | 11.2           |
| EUA          | 21.4                | 331                  | 2.1          | 3.7            |
| China        | 14.3                | 1439                 | 2.9          | 3.8            |
| Alemanha     | 3.8                 | 83                   | 1.4          | 3.2            |
| Japão        | 4.9                 | 126                  | 0.5          | 2.8            |
| França       | 2.6                 | 67                   | 1.8          | 8.1            |
| Reino Unido  | 2.8                 | 67                   | 2.5          | 4.1            |
| Canadá       | 1.7                 | 38                   | 1.9          | 5.7            |

(a) Compare a semelhan ̧ca entre o Brasil e outros pa ́ıses utilizando a distˆancia euclidiana entre
os vetores de caracter ́ısticas (PIB, Popula ̧c ̃ao, Infla ̧c ̃ao, Desemprego).


In [16]:
nomes = ["Brasil", "EUA", "China", "Alemanha", "Japão", "França", "Reino Unido", "Canadá"]
paises = np.array([
    [2.1, 213, 3.2, 11.2],   # Brasil
    [21.4, 331, 2.1, 3.7],   # EUA
    [14.3, 1439, 2.9, 3.8],  # China
    [3.8, 83, 1.4, 3.2],     # Alemanha
    [4.9, 126, 0.5, 2.8],    # Japão
    [2.6, 67, 1.8, 8.1],     # França
    [2.8, 67, 2.5, 4.1],     # Reino Unido
    [1.7, 38, 1.9, 5.7]      # Canadá
])

for i in range(1, paises.shape[0]):
    distancia = np.linalg.norm(paises[0] - paises[i])
    print(f"Brasil - {nomes[i]}: {distancia}")
    

Brasil - EUA: 119.80797135416324
Brasil - China: 1226.083068148321
Brasil - Alemanha: 130.26945152260373
Brasil - Japão: 87.49108526015665
Brasil - França: 146.04047384201408
Brasil - Reino Unido: 146.17588720442234
Brasil - Canadá: 175.09169026541494


(b) Fa ̧ca a padroniza ̧c ̃ao dos dados utilizando a t ́ecnica de z-score em cada uma das carac-
ter ́ısticas. Ap ́os a padroniza ̧c ̃ao, compare novamente a semelhan ̧ca entre os pa ́ıses. Explique
a diferen ̧ca nos resultados comparados com o item anterior.

In [21]:
zscore = np.zeros_like(paises)

zscore = (paises - np.mean(paises, axis=0)) / np.std(paises, axis=0)

print(zscore)

[[-0.68224933 -0.18680919  1.44765713  2.15035987]
 [ 2.18023155  0.08038456  0.07783103 -0.59478039]
 [ 1.12719454  2.58928853  1.07406819 -0.55817852]
 [-0.43011371 -0.48117518 -0.79387649 -0.77778974]
 [-0.26696713 -0.38380796 -1.9146433  -0.92419722]
 [-0.60809179 -0.51740484 -0.29575791  1.01570189]
 [-0.57842878 -0.51740484  0.57594961 -0.44837291]
 [-0.74157536 -0.5830711  -0.17122826  0.13725701]]


(c) Compute a matriz de correla ̧c ̃ao entre os pa ́ıses.

In [38]:
correlacao = np.zeros((paises.shape[0], paises.shape[0]))
paises_media = np.mean(paises, axis = 0)
paises_centrado = paises - paises_media

for i in range(paises.shape[0]):
    vi = paises_centrado[i, :]
    for j in range(paises.shape[0]):
        vj = paises_centrado[j, :]
        correlacao[i, j] = np.dot(vi, vj) / (np.linalg.norm(vi) * np.linalg.norm(vj))

print("Matriz de Correlacao Normal")
print(np.round(correlacao, 4))

#fazendo utilizando o zscore
for i in range(paises.shape[0]):
    vi = zscore[i, :]
    for j in range(paises.shape[0]):
        vj = zscore[j, :]
        correlacao[i, j] = np.dot(vi, vj) / (np.linalg.norm(vi) * np.linalg.norm(vj))

print("\nMatriz de Correlacao Zscore")
print(np.round(correlacao, 4))

Matriz de Correlacao Normal
[[ 1.     -0.9434 -0.9963  0.9957  0.995   0.9974  0.9963  0.9968]
 [-0.9434  1.      0.9257 -0.9278 -0.9263 -0.9302 -0.9292 -0.9304]
 [-0.9963  0.9257  1.     -0.9999 -0.9998 -0.9999 -0.9999 -0.9999]
 [ 0.9957 -0.9278 -0.9999  1.      1.      0.9997  1.      0.9999]
 [ 0.995  -0.9263 -0.9998  1.      1.      0.9996  0.9999  0.9998]
 [ 0.9974 -0.9302 -0.9999  0.9997  0.9996  1.      0.9998  0.9999]
 [ 0.9963 -0.9292 -0.9999  1.      0.9999  0.9998  1.      1.    ]
 [ 0.9968 -0.9304 -0.9999  0.9999  0.9998  0.9999  1.      1.    ]]

Matriz de Correlacao Zscore
[[ 1.     -0.439  -0.1088 -0.7061 -0.7702  0.6367  0.1261  0.2544]
 [-0.439   1.      0.4432 -0.1979 -0.0431 -0.6651 -0.4112 -0.8025]
 [-0.1088  0.4432  1.     -0.5443 -0.4239 -0.7145 -0.343  -0.8758]
 [-0.7061 -0.1979 -0.5443  1.      0.9073 -0.0262  0.2843  0.5051]
 [-0.7702 -0.0431 -0.4239  0.9073  1.     -0.004  -0.1446  0.2954]
 [ 0.6367 -0.6651 -0.7145 -0.0262 -0.004   1.     -0.0045  0.7344]
 [ 0