In [38]:
import numpy as np

## Solução dos Mínimos Quadrados

$$
\begin{align}
\hat{x} = arg \min_x \|A x - b \|^2 & \Rightarrow A^TA\hat{x} = A^Tb\\
&\Rightarrow \hat{x} = (A^T A)^{-1}A^Tb\\
&\Rightarrow \hat{x} = A^+b\\
\end{align}
$$

Onde $A^+$ é a pseudo inversa de Moore-Penrose

__OBS__: Se $Ax=b$ possui solução exata, então $\hat{x}$ é a solução

### Verificação direta que $\hat{x}$ é solução

Para todo $x \neq \hat{x}$, vamos mostrar que $\|A\hat{x} -b\|^2 <\  $\|A\x -b\|^2$

__Lembrete__: $ \| u + v|\^2 = (u+v)^T(u+v) = \|u\|^2 + \|v\|^2 + 2 u^Tv$.

Temos:
$$
\begin{align*}
\|Ax-b\|^2 &= \|Ax\  {\color{cyan}- A\hat{x} + A\hat{x}} - b\|^2 \\
&=\|Ax - A\hat{x}\|^2 + \| A\hat{x} - b\|^2 + 2\  \color{yellow}{(Ax - A\hat{x})^T( A\hat{x} - b)}.
\end{align*}
$$

Observe que:

$$
\begin{align*}
\color{yellow}{(Ax - A\hat{x})^T( A\hat{x} - b)} &= (x^TA^T - \hat{x}^TA^T)( A\hat{x} - b)\\
&=(x^T - \hat{x}^T)A^T( A\hat{x} - b)\\
&=(x - \hat{x})^TA^T( A\hat{x} - b)\\
&=(x - \hat{x})^T( A^TA\hat{x} - A^Tb)\\
&=(x - \hat{x})^T( A^TA\hat{x} - A^Tb)\\
&=(x - \hat{x})^T\mathbf{0}\\
&=0\\
\end{align*}
$$

Dessa forma:

$$
\begin{align*}
\|Ax-b\|^2 =\|A(x - \hat{x})\|^2 + \| A\hat{x} - b\|^2.
\end{align*}
$$

como $\|A(x - \hat{x})\|^2 > 0$, pois $A$ tem colunas linearmente independentes e $x - \hat{x} = 0 \iff x = \hat{x}$, temos: 

$$
\begin{align*}
\|Ax-b\|^2 >  \| A\hat{x} - b\|^2.
\end{align*}
$$


In [39]:
# Implementação da solução
A = np.random.rand(10, 3)
b = np.random.rand(10, 1)

#rcond não faz aproximações
#[0] retorna somente as respostas, não todas as estatisticas que ele retorna
x = np.linalg.lstsq(A, b, rcond=0)[0]
print(x, "\n")

#resolvendo o sistema linear, é melhor que calcular a inversa
def mnq_1(A, b):
    M = A.T @ A
    y = A.T @ b
    x = np.linalg.solve(M, y)
    return x

x = mnq_1(A, b)
print(x, "\n")

# SVD
# é possível calcular a pseudo inversa A^+ pelo SVD
# A = UEV.T, com U e V ortonormais e E é uma matriz diagonal
def mnq_svd(A, b):
    U, S, Vt = np.linalg.svd(A, full_matrices=False) #full matrices = U e V sao retangulares
    inv_S = 1 / S #podemos fazer isso pois S é diagonal, ent S^-1 = 1 / S
    pseudo_invA = Vt.T @ np.diag(inv_S) @ U.T
    x = pseudo_invA @ b
    return x

x = mnq_svd(A, b)
print(x, "\n")

# QR
def mnq_qr(A, b):
    Q, R = np.linalg.qr(A)
    y = Q.T @ b
    x = np.linalg.solve(R, y)
    return x

x  = mnq_qr(A, b)
print(x)


[[ 0.80528987]
 [ 0.47515926]
 [-0.26791109]] 

[[ 0.80528987]
 [ 0.47515926]
 [-0.26791109]] 

[[ 0.80528987]
 [ 0.47515926]
 [-0.26791109]] 

[[ 0.80528987]
 [ 0.47515926]
 [-0.26791109]]
