In [14]:
import numpy as np
import numpy.linalg as la
# import scipy.linalg as la

## Resolver Sistemas Lineares

Ax = b

In [15]:
A = np.array([[2,1,1],
              [2,0,2],
              [4,3,4]])
b = np.array([[-1],
              [1],
              [1]])

print(A)
print(b)

[[2 1 1]
 [2 0 2]
 [4 3 4]]
[[-1]
 [ 1]
 [ 1]]


In [16]:
x = la.solve(A,b)
print(x)

# Erro numérico:
r = la.norm(A@x - b)
print(r)

[[-1.16666667]
 [-0.33333333]
 [ 1.66666667]]
2.220446049250313e-16


Solução exata:
$$
\mathbf{x} = \left[ \begin{array}{r} -7/6 \\-1/3 \\ 5/3 \end{array} \right]
$$


# Exemplo: Circuito Elétrico em Paralelo

![Rede de Resistores](data/circuit.png)

O problema é encontrar as correntes $i_1, i_2,..., i_N $

A solução é dada por: $A i = b$

onde:

$$
A = 
\left[
\begin{array}{cccccccc}
2R & -R & 0 & 0 & \cdots & 0 & 0 & 0 \\
-R & 2R & -R & 0 & & 0 & 0  & 0 \\
0 & -R & 2R & -R & \cdots & 0 & 0 & 0 \\
\vdots &  & \vdots &  & \ddots & & \vdots & \\
0 & 0 & 0 & 0 & \cdots & -R & 2R & -R \\
0 & 0 & 0 & 0 & \cdots & 0 & -R & 2R \\
\end{array}
\right]
\hspace{10mm}
\mathbf{b} = \left[ \begin{array}{r} V \\ \vdots \\ V \end{array} \right]
$$

In [17]:
N = 10 #numero
R = 20 #resistencia
V = 110 #voltagem

b = np.full(N, V)
A1 = np.diag(np.full(N, 2*R)) #diagonal principal
A2 = np.diag(np.full(N - 1, -R), 1) #diagonal 1 posicao acima da principal
A3 = np.diag(np.full(N - 1, -R), -1) #diagonal 1 posicao acima da principal

A = A1 + A2 + A3
print(A)

[[ 40 -20   0   0   0   0   0   0   0   0]
 [-20  40 -20   0   0   0   0   0   0   0]
 [  0 -20  40 -20   0   0   0   0   0   0]
 [  0   0 -20  40 -20   0   0   0   0   0]
 [  0   0   0 -20  40 -20   0   0   0   0]
 [  0   0   0   0 -20  40 -20   0   0   0]
 [  0   0   0   0   0 -20  40 -20   0   0]
 [  0   0   0   0   0   0 -20  40 -20   0]
 [  0   0   0   0   0   0   0 -20  40 -20]
 [  0   0   0   0   0   0   0   0 -20  40]]


## Mudança de Base

Sejam duas bases B e C em um espaço vetorial. Queremos encontrar a matriz [A]ᶜᴮ que transforma as coordenadas de um vetor na base C para as coordenadas na base B.

[v]ᴮ = [A]ᶜᴮ [v]ᶜ

Para construir essa matriz, precisamos expressar cada vetor da base C como uma combinação linear dos vetores da base B. Cada uma dessas combinações lineares é um sistema linear a ser resolvido.



In [ ]:
def matriz_mudanca_base(B, C):
    C_mat = np.vstack(C).T
    X = []
    for b_i in B:
        x_i = la.solve(C, b_i)
        X.append(x_i)

    X = np.vstack(X).T
    return X

_IncompleteInputError: incomplete input (1858578815.py, line 1)

## Matriz de transformação linear em diferentes bases:

Seja T uma transformação linear de um espaço vetorial V para U. Sejam $B_1$ e $B_2$ bases de V, e $C_1$ e $C_2$ bases de U. Seja [T]ᴮ¹ᶜ¹ a matriz de T em relação às bases $B_1$ e $C_1$, e [T]ᴮ²ᶜ² a matriz de T em relação às bases $B_2$ e $C_2$. A relação entre essas matrizes é dada por:

$[T]ᴮ²ᶜ² = Q^{-1} [T]ᴮ¹ᶜ¹ P$

onde P é a matriz de mudança de base de B_2 para B_1, e Q é a matriz de mudança de base de C_1 para C_2.